apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nimbles.ivaltryek.github.com
spec:
  group: ivaltryek.github.com
  names:
    kind: Nimble
    plural: nimbles
    singular: nimble
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deployment:
                  type: object
                  properties:
                    image:
                      type: string
                    replicas:
                      type: integer
                      format: int32 
                      default: 1
                    labels:
                      type: object
                      additionalProperties:
                        type: string
                  required:
                    - labels
