apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-nimble-cluster-role
rules:
- apiGroups: ["ivaltryek.github.com"]
  resources: ["nimbles"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-nimble-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: kube-nimble
  namespace: default
roleRef:
  kind: ClusterRole
  name: kube-nimble-cluster-role
  apiGroup: rbac.authorization.k8s.io

