apiVersion: ivaltryek.github.com/v1
kind: Nimble
metadata:
  name: demo-envfrom-secretref
  namespace: test
spec:
  deployment:
    labels:
      app: demo-envfrom-secretref
    containers:
      - image: nginx:stable
        name: nginx
        livenessProbe:
          httpGet:
            port: 80
            path: /
        envFrom:
          - secretRef: secret-ref-single


