apiVersion: ivaltryek.github.com/v1
kind: Nimble
metadata:
  name: demo-envfrom-configmapref-multi
  namespace: test
spec:
  deployment:
    labels:
      app: demo-envfrom-configmapref-multi
    containers:
      - image: nginx:stable
        name: nginx
        livenessProbe:
          httpGet:
            port: 80
            path: /
        envFrom:
          - configMapRef: game-config-env-file
          - configMapRef: config-multi-env-files

