apiVersion: ivaltryek.github.com/v1
kind: Nimble
metadata:
  name: demo-deployment-service-hpa-ing
  namespace: test
spec:
  deployment:
    containers:
      - image: nginx:stable
        name: nginx-stable
        requests:
          cpu: 50m
    labels:
      test: hpa
  service:
    ports:
      - name: http
        port: 80
        targetPort: 80
  hpa:
    min: 2
    max: 4
    resourcePolicy:
      name: cpu
      type: Utilization
      avgUtil: 30
  ingress:
    rules:
      - host: my-example.info
        pathType: Prefix
        path: /
        port: 80


