apiVersion: ivaltryek.github.com/v1
kind: Nimble
metadata:
  name: demo
  namespace: test
spec:
  deployment:
    containers:
      - image: nginx:stable
        name: nginx-stable
      - image: busybox
        name: busybox
        command: ["/bin/sh", "-c", "sleep 1000"]
    labels:
      app: nginx
      env: test
