apiVersion: ivaltryek.github.com/v1
kind: Nimble
metadata:
  name: demo
  namespace: test
spec:
  deployment:
    containers:
      - image: nginx:stable
        name: nginx-stable
        memoryRequest: 50Mi
        cpuRequest: 20m
        memoryLimit: 100Mi
        cpuLimit: 50Mi
      - image: busybox
        memoryRequest: 50Mi
        cpuRequest: 20m
        memoryLimit: 100Mi
        cpuLimit: 50Mi
        name: busybox
        command: ["/bin/sh", "-c", "sleep 1000"]
    labels:
      app: nginx
      env: test
