name: Release kube-nimble

on:
  push:
    tags:
      - 'v0.*'
  workflow_dispatch:

jobs:
  release:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            deb: true
          - os: ubuntu-latest
            target: arm-unknown-linux-musleabihf
          - os: ubuntu-latest
            target: armv7-unknown-linux-musleabihf
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            deb: true
          - os: macos-11
            target: x86_64-apple-darwin
          - os: macos-11
            target: aarch64-apple-darwin
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Get version
        uses: SebRollen/toml-action@v1.2.0
        id: get_version
        with:
          file: Cargo.toml
          field: package.version
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}
      - name: configure cache
        uses: Swatinem/rust-cache@v2.7.3
        with:
          key: ${{ matrix.target }}
      - name: build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bin nmexport --bin crdgen --release --locked --target=${{ matrix.target }} --color=always --verbose
          use-cross: ${{ runner.os == 'Linux'}}
      - name: install cargo-deb
        if: ${{ matrix.deb == true }}
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-deb
      - name: build deb
        if: ${{ matrix.deb == true }}
        uses: actions-rs/cargo@v1
        with:
          command: deb
          args: --no-build --no-strip --output=. --target=${{ matrix.target }}
      - name: Package (*nix)
        run: |
          tar -cv LICENSE README.md target/${{ matrix.target }}/release/nmexport nmexport |
            gzip --best > \
            nmexport-${{ steps.get_version.outputs.value }}-${{ matrix.target }}.tar.gz
          tar -cv LICENSE README.md target/${{ matrix.target }}/release/crdgen crdgen |
            gzip --best > \
            crdgen-${{ steps.get_version.outputs.value }}-${{ matrix.target }}.tar.gz
      - name: generate crd manifest
        run: |
          target/${{ matrix.target }}/release/crdgen > nimble.ivaltryek.github.com.yaml
      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            *.deb
            *.tar.gz
            *.yaml
        

